version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 260415
      MYSQL_DATABASE: project_1
      MYSQL_USER: root
      MYSQL_PASSWORD: 260415
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: openjdk:17-jdk-slim
    container_name: spring_app
    restart: always
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - .:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 260415
    command: ["java", "-jar", "target/AnVD_project-0.0.1-SNAPSHOT.jar"]

volumes:
  mysql_data:
